<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="CodeIgniter Application Test Suite" tests="4" assertions="4" failures="2" errors="0" time="0.163078">
    <testsuite name="Welcome_test" file="C:\xampp\htdocs\group1\application\tests\controllers\Welcome_test.php" fullPackage="Welcome" tests="1" assertions="1" failures="1" errors="0" time="0.032870">
      <testcase name="test_index" class="Welcome_test" file="C:\xampp\htdocs\group1\application\tests\controllers\Welcome_test.php" line="13" assertions="1" time="0.032870">
        <failure type="PHPUnit_Framework_ExpectationFailedException">Welcome_test::test_index
Failed asserting that '&lt;form action="http://localhost/Welcome/checkLogin" method="get"&gt;
	&lt;input type="text" name="id" placeholder="id" required&gt;
	&lt;input type="text" name="password" placeholder="password" required&gt;
	&lt;input type="submit" value="Login"&gt;&lt;/form&gt;
&lt;/form&gt;' contains "&lt;title&gt;Welcome to CodeIgniter&lt;/title&gt;".

C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\Constraint.php:144
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\Constraint.php:91
C:\xampp\htdocs\group1\application\tests\controllers\Welcome_test.php:16
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\TestResult.php:648
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\TestSuite.php:779
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\TestSuite.php:749
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\TestSuite.php:709
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\TextUI\TestRunner.php:350
</failure>
      </testcase>
    </testsuite>
    <testsuite name="Example_model_test" file="C:\xampp\htdocs\group1\application\tests\models\Example_model_test.php" fullPackage="Example.model" tests="1" assertions="1" failures="0" errors="0" time="0.030362">
      <testcase name="test_get_test_list" class="Example_model_test" file="C:\xampp\htdocs\group1\application\tests\models\Example_model_test.php" line="12" assertions="1" time="0.030362"/>
    </testsuite>
    <testsuite name="User_model_test" file="C:\xampp\htdocs\group1\application\tests\models\User_model_test.php" fullPackage="User.model" tests="2" assertions="2" failures="1" errors="0" time="0.099846">
      <testcase name="test_insert_user" class="User_model_test" file="C:\xampp\htdocs\group1\application\tests\models\User_model_test.php" line="12" assertions="1" time="0.016041"/>
      <testcase name="test_login_user" class="User_model_test" file="C:\xampp\htdocs\group1\application\tests\models\User_model_test.php" line="21" assertions="1" time="0.083805">
        <failure type="PHPUnit_Framework_ExpectationFailedException">User_model_test::test_login_user
Failed asserting that false is true.

C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\Constraint.php:144
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\Constraint.php:91
C:\xampp\htdocs\group1\application\tests\models\User_model_test.php:26
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\TestResult.php:648
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\TestSuite.php:779
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\TestSuite.php:749
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\Framework\TestSuite.php:709
C:\xampp\htdocs\group1\vendor\phpunit\phpunit\PHPUnit\TextUI\TestRunner.php:350
</failure>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
